 					;TODO: Try avoiding store fp in stack

;; (defun add(x y)
;;   (+ x y))
;; (add 1 2)

(setq codeadd '((push (:const 1))
		(push (:const 2))
		(push FP)
		(move SP FP)
		(add (:const -1) FP)
		(jsr add)
		(pop FP)
		(add (:const -2) SP)
		(halt)
		(label add)
		(move (fp -2) R1)
		(move (fp -1) R0)
		(add R1 R0)
		(rtn)))
