(setq codefact '((push (:const 4))
		 (move SP FP)
		 (push (:const 1))
		 (jsr fact)
		 (add (:const -1) FP)
		 (add (:const -2) SP)
		 (halt)
		 (label fact)
		 (move (fp -1) R1)
		 (cmp R1 (:const 1))
		 (jeq end)
		 (push R1)
		 (add (:const -1) R1)
		 (push R1)
		 (move SP FP)
		 (push (:const 1))
		 (jsr fact)
		 (add (:const -1) FP)
		 (add (:const -2) SP)
		 (pop R1)
		 (mul R1 R0)
		 (rtn)
		 (label end)
		 (move R1 R0)
		 (rtn)))
