(defun add (x y)
  (+ x y))

(defun sub (x y)
  (- x y))

(defun mul (x y)
  (* x y))

(defun div (x y)
  (/ x y))

(defun compute (op x y)
  (cond
   ((equal op 'add-op) (add x y))
   ((equal op 'sub-op) (sub x y))
   ((equal op 'mul-op) (mul x y))
   ((equal op 'div-op) (div x y))
   (t ("Operation ~S not supported" op))))

(compute 'mul-op x y)

(setq codeop '((label add)
	       (move (fp -2) R1)
	       (move (fp -1) R2)
	       (add R1 R2)
	       (move R2 R0)
	       (rtn)
	       (label sub)
	       (move (fp -2) R1)
	       (move (fp -1) R2)
	       (sub R1 R2)
	       (move R2 R0)
	       (rtn)
	       (label mul)
	       (move (fp -2) R1)
	       (move (fp -1) R2)
	       (mul R1 R2)
	       (move R2 R0)
	       (rtn)))
